// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AquarioMania.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240624212703_firstMigration")]
    partial class firstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AquarioMania.Models.LivingBeingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Behavior")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Family")
                        .HasColumnType("longtext");

                    b.Property<string>("Hardness")
                        .HasColumnType("longtext");

                    b.Property<string>("Life_expectancy")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Origin")
                        .HasColumnType("longtext");

                    b.Property<string>("Ph")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Scientific_name")
                        .HasColumnType("longtext");

                    b.Property<int>("Type_of_life")
                        .HasColumnType("int");

                    b.Property<int>("Type_of_water")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("LivingBeing");
                });
#pragma warning restore 612, 618
        }
    }
}
